## Dealing with Categorical Data

In [1]:
import pandas as pd
# Load Dataset 
# Use the hotel_bookings_wip.csv from module3/notes.ipynb
data_df = pd.read_csv('../data/hotels_booking_wip.csv')

data_df.head()

,Unnamed: 0,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_year,reservation_status_month,reservation_status_day
0,0,Resort Hotel,0,342,2015,July,27,1,0,0,...,NaN,0,Transient,0.0,0,0,Check-Out,2015,7,1
1,1,Resort Hotel,0,737,2015,July,27,1,0,0,...,NaN,0,Transient,0.0,0,0,Check-Out,2015,7,1
2,2,Resort Hotel,0,7,2015,July,27,1,0,1,...,NaN,0,Transient,75.0,0,0,Check-Out,2015,7,2
3,3,Resort Hotel,0,13,2015,July,27,1,0,1,...,304.0,0,Transient,75.0,0,0,Check-Out,2015,7,2
4,4,Resort Hotel,0,14,2015,July,27,1,0,2,...,240.0,0,Transient,98.0,0,1,Check-Out,2015,7,3

In [2]:
# See dataset dtypes
#data_df.dtypes

# Task: Create a list of those columns/features that are of type object.

object_columns = []

#for col in data_df.columns:
    #if data_df[col].dtype == 'object':
        #object_columns.append(col)


# Using a list comprehension with predicate

cat_cols = [col for col in data_df.columns if data_df[col].dtype == 'object']
cat_cols

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status']

In [3]:
# Task: Create a new dataframe from only those columns

cat_df = data_df[cat_cols]
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,July,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,July,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,July,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [4]:
# Task: print unique values of each feature in cat_df

for col in cat_df.columns:
    print(f'{col}: \n{cat_df[col].unique()}')

hotel:
['Resort Hotel' 'City Hotel']
arrival_date_month:
['July' 'August' 'September' 'October' 'November' 'December' 'January'
 'February' 'March' 'April' 'May' 'June']
meal:
['BB' 'FB' 'HB' 'SC' 'Undefined']
country:
['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' 'ROU' 'NOR' 'OMN' 'ARG' 'POL' 'DEU'
 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST' 'CZE'
 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR' 'UKR'
 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO' 'ISR'
 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM' 'HRV'
 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY' 'KWT'
 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN' 'SYC'
 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB' 'CMR'
 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI' 'SAU'
 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB' 'NPL'
 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA' 'KHM'
 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP' 'GLP'
 'KEN' 'LIE' 'GNB' 'MNE' 'UMI' 'MYT' 'FRO' 'MMR' 'PAN' 'BFA' 'LBY' 'MLI'
 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'SLV' 'DMA' 'PYF' 'GUY' 'LCA' 'ATA'
 'GTM' 'ASM' 'MRT' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO']
market_segment:
['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']
distribution_channel:
['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']
reserved_room_type:
['C' 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'B']
assigned_room_type:
['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'L' 'K']
deposit_type:
['No Deposit' 'Refundable' 'Non Refund']
customer_type:
['Transient' 'Contract' 'Transient-Party' 'Group']
reservation_status:
['Check-Out' 'Canceled' 'No-Show']

In [5]:
# Task: Cast the categorical features to the category data type for 'arrival_date_month'ArithmeticError
# # January -> 1, February -> 2, etc.

# Dictionary for month-to-integer mapping
month_map = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6, 
    'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
}

# Apply the mapping to 'arrival_date_month'
cat_df.loc[:,'arrival_date_month'] = cat_df['arrival_date_month'].map(month_map)

# Check the result
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,7,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,7,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,7,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [6]:
# Now do the country hotel feature
# Label encoding from sklearn: conda install scikit-learn

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # Create an object of type LabelEncoder

In [8]:
# Encode country feature
# cat_df['country'] = le.fit_transform(cat_df['country'])
cat_df.loc[:,'country'] = le.fit_transform(cat_df['country']) # new way with .loc

cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,7,BB,59,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,7,BB,59,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,7,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

### One-Hot Encoding

In [9]:
# print all of your categories
cat_df.columns

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type', 'reservation_status'],
      dtype='object')

In [10]:
# One-Hot encoding for All features as one, except: 'arrival_date_month' and 'country'
# Create a new list of columns to be converted
processed_cols = ['country', 'arrival_date_month']
one_hot_cols = [col for col in cat_df.columns if col not in processed_cols]
dummy_df = pd.get_dummies(data=cat_df, columns=one_hot_cols)

dummy_df.head()
# TODO: Fix, 'reservation_status_date' feature

,arrival_date_month,country,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,...,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,7,135,False,True,True,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
1,7,135,False,True,True,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
2,7,59,False,True,True,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
3,7,59,False,True,True,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
4,7,59,False,True,True,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False

In [11]:
# Merge back to original data frame
cat_df = pd.concat([cat_df, dummy_df], axis=1)
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,...,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,Resort Hotel,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,...,True,False,False,False,False,True,False,False,True,False
1,Resort Hotel,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,...,True,False,False,False,False,True,False,False,True,False
2,Resort Hotel,7,BB,59,Direct,Direct,A,C,No Deposit,Transient,...,True,False,False,False,False,True,False,False,True,False
3,Resort Hotel,7,BB,59,Corporate,Corporate,A,A,No Deposit,Transient,...,True,False,False,False,False,True,False,False,True,False
4,Resort Hotel,7,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,...,True,False,False,False,False,True,False,False,True,False

In [12]:
# Drop the original 'object' columns
num_df = data_df.drop(columns=cat_cols, axis=1)

In [13]:
# Now, create your final df
final_df = pd.concat([num_df, cat_df], axis=1)
final_df.head()

,Unnamed: 0,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,0,0,342,2015,27,1,0,0,2,0.0,...,True,False,False,False,False,True,False,False,True,False
1,1,0,737,2015,27,1,0,0,2,0.0,...,True,False,False,False,False,True,False,False,True,False
2,2,0,7,2015,27,1,0,1,1,0.0,...,True,False,False,False,False,True,False,False,True,False
3,3,0,13,2015,27,1,0,1,1,0.0,...,True,False,False,False,False,True,False,False,True,False
4,4,0,14,2015,27,1,0,2,2,0.0,...,True,False,False,False,False,True,False,False,True,False

In [14]:
# Save it as a new file
final_df.to_csv('../data/hotel_booking_new.csv')

### Correlation Analysis

In [15]:
# Create a correlation matrix
corr_matrix = final_df.corr(numeric_only=True)

corr_matrix

,Unnamed: 0,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
Unnamed: 0,1.000000,-0.266802,-0.039291,0.322684,-0.055616,0.003030,-0.156257,-0.215218,0.002813,-0.027196,...,0.026454,-0.015783,-0.037110,-0.094606,-0.011451,0.068974,-0.022634,-0.260761,0.266802,-0.039826
is_canceled,-0.266802,1.000000,0.182933,0.087449,0.001180,0.005381,0.060386,0.083838,0.081074,0.066124,...,-0.156617,0.165237,-0.002606,-0.048876,-0.031168,0.128014,-0.109269,0.970963,-1.000000,0.175584
lead_time,-0.039291,0.182933,1.000000,0.138387,0.101223,0.009439,0.235428,0.312606,0.141754,0.022918,...,-0.168096,0.167832,0.026667,0.065756,-0.025530,-0.162580,0.151732,0.193604,-0.182933,-0.033650
arrival_date_year,0.322684,0.087449,0.138387,1.000000,-0.513891,-0.009932,0.005044,0.003834,0.037800,0.042053,...,0.018924,-0.019296,-0.001758,-0.168153,-0.017444,0.170529,-0.094544,0.091509,-0.087449,-0.011802
arrival_date_week_number,-0.055616,0.001180,0.101223,-0.513891,1.000000,0.092946,0.026872,0.028235,0.025066,0.013653,...,0.000519,0.003975,-0.013992,0.091170,0.013617,-0.059934,0.013904,0.005788,-0.001180,-0.018897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
customer_type_Transient,0.068974,0.128014,-0.162580,0.170529,-0.059934,0.004972,-0.019334,-0.045014,0.093845,0.079506,...,0.018199,0.001012,-0.062282,-0.419220,-0.170411,1.000000,-0.849843,0.127890,-0.128014,0.007689
customer_type_Transient-Party,-0.022634,-0.109269,0.151732,-0.094544,0.013904,0.005188,-0.045782,-0.035188,-0.125019,-0.074034,...,-0.024373,0.003841,0.067320,-0.076157,-0.030958,-0.849843,1.000000,-0.109716,0.109269,-0.004288
reservation_status_Canceled,-0.260761,0.970963,0.193604,0.091509,0.005788,0.004592,0.058112,0.082611,0.089174,0.067113,...,-0.160196,0.168947,-0.002460,-0.047941,-0.030855,0.127890,-0.109716,1.000000,-0.970963,-0.065027
reservation_status_Check-Out,0.266802,-1.000000,-0.182933,-0.087449,-0.001180,-0.005381,-0.060386,-0.083838,-0.081074,-0.066124,...,0.156617,-0.165237,0.002606,0.048876,0.031168,-0.128014,0.109269,-0.970963,1.000000,-0.175584
reservation_status_No-Show,-0.039826,0.175584,-0.033650,-0.011802,-0.018897,0.003547,0.012746,0.009751,-0.028787,-0.000360,...,0.005943,-0.005996,-0.000747,-0.006592,-0.003037,0.007689,-0.004288,-0.065027,-0.175584,1.000000

### Correlation and Causation

**Correlation**: A measure of the extent of interdependence between variables 

**Causation**: The relationship between cause and effect between two variables 

#### Pearson Correlation
Measures the linear dependence between two variables. The result coefficient is a value between `-1 and +1` where:

- `1`: Perfect positive correlation
- `0`: No linear correlation
- `-1`: Perfect negative correlation

Note: `Pearson` correlation is the default method in pandas for the corr() method

In [16]:
# Do a correlation between 'is_canceled' and 'children' features 
corr_matrix_two = final_df[['is_canceled', 'children']].corr()
corr_matrix_two

             is_canceled  children
is_canceled     1.000000  0.066124
children        0.066124  1.000000

Sometimes we want to know the significance of the correlation estimate

#### P-value
The probability value that the correlation between the variables is statistically significant 

Normally we choose a significance level of `0.05`, which means we are `95%` confident.

P-Values
- $<$ 0.001: We say there is `strong` evidence 
- $<$ 0.05: We say there is `moderate` evidence 
- $<$ 0.1: We say there is `weak` evidence 
- $>$ 0.1: We say there is `no` evidence

In [19]:
# conda install scipy
from scipy.stats import pearsonr, spearmanr

corr, p_value = pearsonr(final_df['is_canceled'], final_df['children'])
print(f'Pearson Correlation:[{corr}]\n P_value:[{p_value}]')

Pearson Correlation:[0.06612422800100211]
 P_value:[1.7836581112118683e-84]